### ISSUE TITLE
Crash during installation of theme

### ISSUE THREAD

**Issue by DavidSichau** [grueneschweiz/2018.gruene.ch#135]
Hello,

I tried to install the latest version of this theme and it resulted in the following crash:

Ein Fehler vom Typ E_ERROR wurde in der Zeile 87 der Datei .../wp-content/themes/les-verts/lib/_loader.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined function is_plugin_active() in ...h/wp-content/themes/les-verts/lib/_loader.php:87
Stack trace:
#0 .../wp-content/themes/les-verts/functions.php(27): require_once()
#1 .../wp-settings.php(546): include('/home/martinam/...')
#2 .../wp-config.php(97): require_once('/home/martinam/...')
#3 .../wp-load.php(50): require_once('/home/martinam/...')
#4 .../wp-admin/admin.php(34): require_once('/home/martinam/...')
#5 .../wp-admin/themes.php(10): require_once('/home/martinam/...')
#6 {main}
  thrown

Details about my System:

WordPress-Version 5.8.2
Aktuelles Theme: Les Verts (Version 0.26.2) Aktuelles Plugin:  (Version ) PHP-Version 7.4.24

I also tried version Version 0.26.1, 0.24.0 of the theme resulting in the same error.

**Comment by cyrillbolliger** [comment]
Hi

This line will be removed in the upcomming release.

**Comment by cyrillbolliger** [comment]
fixed by #137
