### ISSUE TITLE
Missing I18n / L10n in Category Page

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#20]
Text "Here you will find any content categorized under" is not properly internationalized or not localized in german and french
https://gruene.ch/?category_name=medienmitteilungen+energie-und-klima and
https://verts.ch/?category_name=communiques+energie-et-climat

see:
![image](https://user-images.githubusercontent.com/12211421/52177130-e6bd2080-27bc-11e9-9644-9f91f20ef113.png)
![image](https://user-images.githubusercontent.com/12211421/52177189-a8743100-27bd-11e9-8fe3-6103d4c5e0f3.png)

**Comment by cyrillbolliger** [comment]
Thnx for pointing this out!
