### ISSUE TITLE
Add Bluesky as possible SoMe Account

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#208]
https://bsky.app/ seems to be really taking off in switzerland as a Twitter/X alternative. 

And (as of 15.12.2023) https://threads.net is available in EU/CH as well and might be taking off faster even than Bluesky (because of the inherited Network from Instagram)

**Comment by cyrillbolliger** [comment]
I suggest to add it as soon as it hits 1% on https://gs.statcounter.com/social-media-stats/all/switzerland/#monthly-202210-202310

**Comment by politbuero-kampagnen** [comment]
> I suggest to add it as soon as it hits 1% on https://gs.statcounter.com/social-media-stats/all/switzerland/#monthly-202210-202310

I would suggest to reeval whet it hits 0.5% - because (as of december 15 2023) linkedin is at 0.76% but is certainly an important option for politicans and their specific public.

**Comment by Michael-Schaer** [comment]
TikTok, Bluesky und Threads sind nun hinzugefügt:
https://github.com/grueneschweiz/2018.gruene.ch/pull/221
