### ISSUE TITLE
Partially missing french translation in Link to category (bottom of thematic pages)

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#21]
on the bottom of the theme-pages there are links to all media releases / vernehmlassungen.

**In german, the link text is correct:**
https://gruene.ch/umwelt/energie-und-klima/klima
"ALLE 208 MEDIENMITTEILUNGEN ZUM THEMA ENERGIE UND KLIMA" resp.
"ALLE 25 VERNEHMLASSUNGSANTWORTEN ZUM THEMA ENERGIE UND KLIMA"
![image](https://user-images.githubusercontent.com/12211421/52177266-921aa500-27be-11e9-8271-b2f11fc072d1.png)

**in french, however, the second part of the link text after the # of entries ist missing:**
https://verts.ch/environnement/energie-et-climat/climat
"AFFICHER L’ENSEMBLE DES 134"
"AFFICHER L’ENSEMBLE DES 16"

![image](https://user-images.githubusercontent.com/12211421/52177254-70b9b900-27be-11e9-931e-69ea394e0d3c.png)

**Comment by cyrillbolliger** [comment]
closed in 1225ac6e8f7dee73931eb6ea017ce2755c389768
