### ISSUE TITLE
Search issue: Keyword search only searches titles, not body of entries

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#23]
When searching with the top level search (e.g. with keyword "Wohnungen") not all articles containing the keyword are shown.
![image](https://user-images.githubusercontent.com/12211421/52207740-a7570880-287e-11e9-9671-6ef4126e69b6.png)

This search should (among other items) show the following Media release:
https://gruene.ch/medienmitteilungen/ausbau-der-wohnbaufoerderung-ist-ueberfaellig
that contains the keyword "Wohnungen".

However, it does not show this in the results list here: [https://gruene.ch/?s=wohnungen](https://gruene.ch/?s=wohnungen)

**My guess is that the search function only searches within the TITLES but not in the bodies of the blog-entries.** (all three results being shown containt the keyword "Wohnungen" in the title)

**Comment by cyrillbolliger** [comment]
This is on the roadmap.
