### ISSUE TITLE
Implement more intuitive Search Result Order

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#37]
When searching a Keyword, the results are shown in a seemingly unordered way. Example:
[https://gruene.ch/?s=klima](https://gruene.ch/?s=klima). See below how the site displays results for this query.

**Proposal:**
Define an intuitive search order that shows recent, generic and actionable content before archived stuff. A smart ordering strategy most certainly has to be devised.

Just my to cents about possible ingredients of a smart ordering strategy:

1. at least all entries within an identical category-set (eg. "Energie und Klima, Medienmitteilungen, Umwelt") should be ordered _by date desc_ (i.e. newest one first) - even if they eventually are not grouped together
1. consider grouping results into content categories: a) actionable content b) static content c) press releases
1. consider introducing linked category titles before result-list, ideally with a result counter. A click on the Category title would apply a filter that only displays the results In the given category, In the example stated, this could be:
- Grüne  Grundsatzposition (1)
- Kampagne (1)
- Events (1)
- Medienmitteilungen (...zig...)

**Example**
[https://gruene.ch/?s=klima](https://gruene.ch/?s=klima) displays results in the following "order":

Mehr Einsatz der Schweiz für das Klima, bitte!
22. September 2014 Energie und Klima, Medienmitteilungen, Umwelt
`this is a Press release, part of /kategorie/medienmitteilungen`

Werde jetzt Klima-Aktivist*in
Energie und Klima, Kampagne, Umwelt
`This is a call to action form, part of /kategorie/kampagne`

Klima-Allianz fordert wirksames Klimagesetz
19. Oktober 2009 Energie und Klima, Medienmitteilungen, Umwelt
`this is a Press release`

Grüne fordern echte Massnahmen für den Schutz des Klimas
27. Mai 2010 Energie und Klima, Medienmitteilungen, Umwelt
`this is a Press release`

Klima
Energie und Klima, Umwelt
`This is a static content, part of neither /kategorie/medienmitteilungen nor /kategorie/kapagne nor /events/`

Einreichung der Klima-Initiative
29. Februar 2008 Energie und Klima, Medienmitteilungen, Umwelt
`this is a Press release`
(...)

Klima: Public Hearing 
24. Mai 2019
`this is an event, part of /events`

**Comment by cyrillbolliger** [comment]
Yes, the search isn't optimal yet. There is work to do. There was a new major release of the [Search WP](https://searchwp.com/) plugin, which we use. I'll check the changes and new possibilities occasionally, hopefully we can implement brings the needed improvements with this plugin.

**Comment by politbuero-kampagnen** [comment]
There might be a possibility to add at least a search order or results
grouping using the hooks

https://searchwp.com/docs/hooks/searchwp_query_orderby/  or
https://searchwp.com/docs/hooks/searchwp_results/

Am Fr., 19. Apr. 2019 um 13:47 Uhr schrieb Cyrill Bolliger <
notifications@github.com>:

**Comment by politbuero-kampagnen** [comment]
To mitigate the problems with the generic search, it could be a solution to add a "detail search" form (Label "Search within this category") in the category templates, that only pull up results from entries that belong to the respective category. 

![image](https://user-images.githubusercontent.com/12211421/60336944-00e0e080-99a2-11e9-9e9e-ae680d7e2d0e.png)

**Comment by cyrillbolliger** [comment]
With the release of https://github.com/grueneschweiz/2018.gruene.ch/releases/tag/0.9.0, search results are now filterable by categories.

**Comment by politbuero-kampagnen** [comment]
Cool!

Cyrill Bolliger <notifications@github.com> schrieb am Mo., 22. Juli 2019,
20:15:
