### ISSUE TITLE
Enhance 404 Page with link to https://web.archive.org/web/

### ISSUE THREAD

**Issue by politbuero-kampagnen** [grueneschweiz/2018.gruene.ch#38]
as of now, many PDF-Files are not migrated (yet?) to the new website. As a consequence, links to these files in old Press Releases are not working and do lead the user to the 404 Page.

However, the respective PDF Files might still be available through web.archive.org. The same might be the case for other internal links, that give a 404 error.

Proposal: enhance the 404 page with a link

`Möglicherweise findest Du die gesuchte Website noch <a href="https://web.archive.org/web/$the_incorrect_url_that_led_us_here" target="_blank">im Internet-Archiv web.archive.org</a>`

**Comment by cyrillbolliger** [comment]
after internal discussion, we deiced against it. since this issue was opened, we've finished the migration of content and we don't want to promote the content we didn't migrate ;) 
additionally we've improved the search and we're on the way of making it even better.
